const token = (name) => `hsl(var(--color-${name}) / <alpha-value>)`

/** @type {import('tailwindcss').Config} */
// Design tokens mirror the original mockups' cozy/homey theme (mockups/styles.css).
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Warm, homey palette
        'bg-top': token('bg-top'),
        'bg-bottom': token('bg-bottom'),
        'bg-highlight': token('bg-highlight'),
        card: token('card'),
        ink: token('ink'),
        'ink-soft': token('ink-soft'),
        line: token('line'),
        accent: token('accent'),
        'accent-deep': token('accent-deep'),
        'accent-soft': token('accent-soft'),
        sage: token('sage'),
        'surface-hover': token('surface-hover'),
        'surface-muted': token('surface-muted'),
        'surface-disabled': token('surface-disabled'),
        'surface-completed': token('surface-completed'),
        'surface-expired-border': token('surface-expired-border'),
        'placeholder-muted': token('placeholder-muted'),
        'warm-text-muted': token('warm-text-muted'),
        'border-hover': token('border-hover'),
        'border-warm': token('border-warm'),
        'danger-soft': token('danger-soft'),
        'danger-soft-border': token('danger-soft-border'),
        'danger-soft-hover': token('danger-soft-hover'),
        'success-soft': token('success-soft'),
        'success-soft-border': token('success-soft-border'),
        'success-panel': token('success-panel'),
        'success-panel-end': token('success-panel-end'),
        'success-panel-strong': token('success-panel-strong'),
        'success-panel-hover': token('success-panel-hover'),
        'success-panel-border': token('success-panel-border'),
        'success-panel-text': token('success-panel-text'),
        'jam-panel': token('jam-panel'),
        'jam-border': token('jam-border'),
        'jam-border-muted': token('jam-border-muted'),
        'jam-action': token('jam-action'),
        'jam-action-hover': token('jam-action-hover'),
        'jam-action-text': token('jam-action-text'),
        'check-surface': token('check-surface'),
        'check-border': token('check-border'),
        'neutral-action': token('neutral-action'),
        'response-pending': token('response-pending'),
        'response-pending-text': token('response-pending-text'),
        'completed-pill': token('completed-pill'),
        'live-border': token('live-border'),
        'live-bg-start': token('live-bg-start'),
        'live-bg-end': token('live-bg-end'),
        'live-bg-strong': token('live-bg-strong'),
        'live-text': token('live-text'),
        'you-border': token('you-border'),
        'you-action-border': token('you-action-border'),
        'you-hover': token('you-hover'),
        // Status dot colors
        'status-green': token('status-green'),
        'status-hover-green': token('status-hover-green'),
        'status-red': token('status-red'),
        'status-purple': token('status-purple'),
        'status-blue': token('status-blue'),
        'status-amber': token('status-amber'),
        'status-hover-red': token('status-hover-red'),
        'status-grey': token('status-grey'),
      },
      fontFamily: {
        display: ['Fraunces', 'Georgia', 'serif'],
        sans: ['Nunito', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        lg: '28px',
        md: '18px',
        sm: '12px',
      },
      boxShadow: {
        soft: 'var(--shadow-soft)',
        card: 'var(--shadow-card)',
      },
      keyframes: {
        pulse: {
          '0%': { boxShadow: '0 0 0 0 rgba(90, 164, 105, .5)' },
          '70%': { boxShadow: '0 0 0 9px rgba(90, 164, 105, 0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(90, 164, 105, 0)' },
        },
        // Pull-to-refresh dots: a gentle rise + brighten, staggered per dot.
        'dot-bounce': {
          '0%, 80%, 100%': { transform: 'translateY(0)', opacity: '0.4' },
          '40%': { transform: 'translateY(-5px)', opacity: '1' },
        },
      },
      animation: {
        pulse: 'pulse 1.8s infinite',
        'dot-bounce': 'dot-bounce 1.1s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
