/** @type {import('tailwindcss').Config} */
// Design tokens mirror the original mockups' cozy/homey theme (mockups/styles.css).
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        // Warm, homey palette
        'bg-top': '#f6ecdd',
        'bg-bottom': '#efdfca',
        'bg-highlight': '#fff6ea',
        card: '#fffdf8',
        ink: '#3d342a',
        'ink-soft': '#8a7c6a',
        line: '#e7dccb',
        accent: '#c97b5a',
        'accent-deep': '#b3613f',
        'accent-soft': '#f3e1d6',
        sage: '#8a9a7b',
        'surface-hover': '#faf6ef',
        'surface-muted': '#f5f0e8',
        'surface-disabled': '#f7f3ec',
        'surface-completed': '#eeeeec',
        'surface-expired-border': '#ddd4c7',
        'placeholder-muted': '#b6a995',
        'warm-text-muted': '#756958',
        'border-hover': '#d9c9b3',
        'border-warm': '#e1cdbb',
        'danger-soft': '#fbeae6',
        'danger-soft-border': '#e8c5bf',
        'danger-soft-hover': '#f6ddd7',
        'success-soft': '#bfedc9',
        'success-soft-border': '#94d9a3',
        'success-panel': '#eef3e7',
        'success-panel-end': '#e7efdd',
        'success-panel-strong': '#d9eadc',
        'success-panel-hover': '#c8e3ce',
        'success-panel-border': '#d6e2c5',
        'success-panel-text': '#50603f',
        'jam-panel': '#f1fbf3',
        'jam-border': '#bde4c7',
        'jam-border-muted': '#b8d6bf',
        'jam-action': '#e7f4ea',
        'jam-action-hover': '#d7ebdc',
        'jam-action-text': '#4b7a54',
        'check-surface': '#f4f1ea',
        'check-border': '#bdbdb6',
        'neutral-action': '#d8d8d3',
        'response-pending': '#a8a8a8',
        'response-pending-text': '#777771',
        'completed-pill': '#e1e1dd',
        'live-border': '#e8b9ae',
        'live-bg-start': '#fff0ec',
        'live-bg-end': '#fbe2dc',
        'live-bg-strong': '#e3a496',
        'live-text': '#713c32',
        'you-border': '#ecc9b6',
        'you-action-border': '#e6c2ad',
        'you-hover': '#fff3ec',
        // Status dot colors
        'status-green': '#5aa469',
        'status-hover-green': '#4f7b32',
        'status-red': '#cf6b5e',
        'status-purple': '#9a78b8',
        'status-blue': '#6a86b8',
        'status-amber': '#d39a4f',
        'status-hover-red': '#a0443b',
        'status-grey': '#757575',
      },
      fontFamily: {
        display: ['Fraunces', 'Georgia', 'serif'],
        sans: ['Nunito', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        lg: '28px',
        md: '18px',
        sm: '12px',
      },
      boxShadow: {
        soft: '0 6px 18px -8px rgba(94, 66, 41, 0.3)',
        card: '0 18px 50px -18px rgba(94, 66, 41, 0.35)',
      },
      keyframes: {
        pulse: {
          '0%': { boxShadow: '0 0 0 0 rgba(90, 164, 105, .5)' },
          '70%': { boxShadow: '0 0 0 9px rgba(90, 164, 105, 0)' },
          '100%': { boxShadow: '0 0 0 0 rgba(90, 164, 105, 0)' },
        },
        // Pull-to-refresh dots: a gentle rise + brighten, staggered per dot.
        'dot-bounce': {
          '0%, 80%, 100%': { transform: 'translateY(0)', opacity: '0.4' },
          '40%': { transform: 'translateY(-5px)', opacity: '1' },
        },
      },
      animation: {
        pulse: 'pulse 1.8s infinite',
        'dot-bounce': 'dot-bounce 1.1s ease-in-out infinite',
      },
    },
  },
  plugins: [],
}
